name: Rebuild CLI documentation

on: push
jobs:
  rebuild-cli-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build CLI
        run: ./gradlew installDist --build-cache
      - run: curl -s "https://get.sdkman.io" | bash
      - run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh" &&
          sdk install java 8.0.292.hs-adpt &&
          sdk install kotlin &&
          sdk install kscript &&
          kscript ./modules/cli/scripts/rebuild-doc.kts